local store = require('camouflage.checks.store')

describe('camouflage.checks.store', function()
  before_each(function()
    store._reset()
  end)

  it('set/get round-trip', function()
    store.set(1, 5, 'pwned', { severity = 'error', text = 'PWNED 1' })
    local r = store.get(1, 5, 'pwned')
    assert.is_table(r)
    assert.equals('PWNED 1', r.text)
  end)

  it('returns nil for missing entries', function()
    assert.is_nil(store.get(1, 5, 'pwned'))
  end)

  it('get_line returns all checks for a line', function()
    store.set(1, 0, 'pwned', { severity = 'error', text = 'A' })
    store.set(1, 0, 'expiry', { severity = 'warning', text = 'B' })
    local line = store.get_line(1, 0)
    assert.is_table(line.pwned)
    assert.is_table(line.expiry)
  end)

  it('set nil removes the check', function()
    store.set(1, 0, 'pwned', { severity = 'error', text = 'x' })
    store.set(1, 0, 'pwned', nil)
    assert.is_nil(store.get(1, 0, 'pwned'))
  end)

  it('removing last check on a line cleans up the line entry', function()
    store.set(1, 0, 'pwned', { severity = 'error', text = 'x' })
    store.set(1, 0, 'pwned', nil)
    assert.same({}, store.get_line(1, 0))
    assert.same({}, store.lines_with_results(1))
  end)

  it('lines_with_results returns sorted line numbers', function()
    store.set(1, 5, 'pwned', { severity = 'error', text = 'x' })
    store.set(1, 1, 'pwned', { severity = 'error', text = 'x' })
    store.set(1, 3, 'expiry', { severity = 'info', text = 'x' })
    assert.same({ 1, 3, 5 }, store.lines_with_results(1))
  end)

  it('clear_check removes a single check across the buffer', function()
    store.set(1, 0, 'pwned', { severity = 'error', text = 'a' })
    store.set(1, 2, 'pwned', { severity = 'error', text = 'b' })
    store.set(1, 2, 'expiry', { severity = 'info', text = 'c' })
    local affected = store.clear_check(1, 'pwned')
    assert.same({ 0, 2 }, affected)
    assert.is_nil(store.get(1, 0, 'pwned'))
    assert.is_nil(store.get(1, 2, 'pwned'))
    assert.is_not_nil(store.get(1, 2, 'expiry'))
  end)

  it('clear_buffer wipes everything', function()
    store.set(1, 0, 'pwned', { severity = 'error', text = 'x' })
    store.set(2, 0, 'pwned', { severity = 'error', text = 'x' })
    store.clear_buffer(1)
    assert.same({}, store.lines_with_results(1))
    assert.same({ 0 }, store.lines_with_results(2))
  end)
end)
